# Based on https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html
name: Sync Two Wiki Repos

on:
  # Merged PRs
  push:
    branches: [master]
  # Weekly
  schedule:
    # https://crontab.guru/#0_12_*_*_1
    - cron: "0 12 * * 1"
  # Whenever someone asks
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

        # Setup Git
      - run: git config user.name "typescript-bot"
      - run: git config user.email "bot@typescriptlang.org"

        # Replace remotes with auth'd versions, then pull the .wiki version (the one people can't PR to)
        # then merge in any changes from here and push
      - 
        run: |
          git remote add upstream https://$GITHUB_TOKEN@github.com/microsoft/TypeScript.wiki.git > /dev/null 2>&1
          git remote remove origin
          git remote add origin https://$GITHUB_TOKEN@github.com/microsoft/TypeScript-wiki.git > /dev/null 2>&1
          git remote add upstream https://$GITHUB_TOKEN@github.com/microsoft/TypeScript.wiki.git > /dev/null 2>&1
          git fetch origin
          git fetch upstream
          git merge upstream/master --no-edit
          git push origin HEAD:master > /dev/null 2>&1
          git push upstream HEAD:master > /dev/null 2>&1
        env:
          GITHUB_TOKEN: ${{ secrets.TS_BOT_TOKEN }}

